### ISSUE TITLE
run code error

### ISSUE THREAD

**Issue by tytcc** [eth-nn-physics/nn_physical_concepts#1]
When i run the qubit_example, I always get the error as follow:
`edq.create_data(1, 5, 100000, 'qubit_example')`
  File "E:/abc/nn_physical_concepts/scinet/example.py", line 6, in <module>
    edq.create_data(1, 5, 100000, 'qubit_example')
  File "e:\abc\nn_physical_concepts\scinet\ed_quantum.py", line 31, in create_data
    f = gzip.open(io.data_path + file_name + ".plk.gz", 'wb')
AttributeError: module 'io' has no attribute 'data_path'

How can i solve the problem?

**Comment by tonymetger** [comment]
Hi, I'm sorry to hear that you've run into a problem. 
Unfortunately, I'm not able to reproduce this on my end, it works just fine for me. Could you provide more details to reproduce the error? Have you added the correct folder to your pythonpath as described in the readme?
(As a side remark, the actual qubit example from the paper can be found in the qubit branch, the example in the master branch is just to test that your installation is working, and to demonstrate how to train a network.)

**Comment by tytcc** [comment]
Thanks for the answer.
I found the reason of the error: I used python3.6 instead of python2.7. It seems that io.py has the same name with the system function. Thus, I changed the name of io.py. And the error never happen again.
